# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/blanc_p/tek2/indie/OOP_indie_studio_2018

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/blanc_p/tek2/indie/OOP_indie_studio_2018

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blanc_p/tek2/indie/OOP_indie_studio_2018/CMakeFiles /home/blanc_p/tek2/indie/OOP_indie_studio_2018/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blanc_p/tek2/indie/OOP_indie_studio_2018/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

src/Indie.o: src/Indie.cpp.o

.PHONY : src/Indie.o

# target to build an object file
src/Indie.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Indie.cpp.o
.PHONY : src/Indie.cpp.o

src/Indie.i: src/Indie.cpp.i

.PHONY : src/Indie.i

# target to preprocess a source file
src/Indie.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Indie.cpp.i
.PHONY : src/Indie.cpp.i

src/Indie.s: src/Indie.cpp.s

.PHONY : src/Indie.s

# target to generate assembly for a file
src/Indie.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Indie.cpp.s
.PHONY : src/Indie.cpp.s

src/Part/Game/Game.o: src/Part/Game/Game.cpp.o

.PHONY : src/Part/Game/Game.o

# target to build an object file
src/Part/Game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/Game.cpp.o
.PHONY : src/Part/Game/Game.cpp.o

src/Part/Game/Game.i: src/Part/Game/Game.cpp.i

.PHONY : src/Part/Game/Game.i

# target to preprocess a source file
src/Part/Game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/Game.cpp.i
.PHONY : src/Part/Game/Game.cpp.i

src/Part/Game/Game.s: src/Part/Game/Game.cpp.s

.PHONY : src/Part/Game/Game.s

# target to generate assembly for a file
src/Part/Game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/Game.cpp.s
.PHONY : src/Part/Game/Game.cpp.s

src/Part/Game/maps/BasicMap.o: src/Part/Game/maps/BasicMap.cpp.o

.PHONY : src/Part/Game/maps/BasicMap.o

# target to build an object file
src/Part/Game/maps/BasicMap.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/BasicMap.cpp.o
.PHONY : src/Part/Game/maps/BasicMap.cpp.o

src/Part/Game/maps/BasicMap.i: src/Part/Game/maps/BasicMap.cpp.i

.PHONY : src/Part/Game/maps/BasicMap.i

# target to preprocess a source file
src/Part/Game/maps/BasicMap.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/BasicMap.cpp.i
.PHONY : src/Part/Game/maps/BasicMap.cpp.i

src/Part/Game/maps/BasicMap.s: src/Part/Game/maps/BasicMap.cpp.s

.PHONY : src/Part/Game/maps/BasicMap.s

# target to generate assembly for a file
src/Part/Game/maps/BasicMap.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/BasicMap.cpp.s
.PHONY : src/Part/Game/maps/BasicMap.cpp.s

src/Part/Game/maps/Block/Animation.o: src/Part/Game/maps/Block/Animation.cpp.o

.PHONY : src/Part/Game/maps/Block/Animation.o

# target to build an object file
src/Part/Game/maps/Block/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Animation.cpp.o
.PHONY : src/Part/Game/maps/Block/Animation.cpp.o

src/Part/Game/maps/Block/Animation.i: src/Part/Game/maps/Block/Animation.cpp.i

.PHONY : src/Part/Game/maps/Block/Animation.i

# target to preprocess a source file
src/Part/Game/maps/Block/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Animation.cpp.i
.PHONY : src/Part/Game/maps/Block/Animation.cpp.i

src/Part/Game/maps/Block/Animation.s: src/Part/Game/maps/Block/Animation.cpp.s

.PHONY : src/Part/Game/maps/Block/Animation.s

# target to generate assembly for a file
src/Part/Game/maps/Block/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Animation.cpp.s
.PHONY : src/Part/Game/maps/Block/Animation.cpp.s

src/Part/Game/maps/Block/Bombe.o: src/Part/Game/maps/Block/Bombe.cpp.o

.PHONY : src/Part/Game/maps/Block/Bombe.o

# target to build an object file
src/Part/Game/maps/Block/Bombe.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bombe.cpp.o
.PHONY : src/Part/Game/maps/Block/Bombe.cpp.o

src/Part/Game/maps/Block/Bombe.i: src/Part/Game/maps/Block/Bombe.cpp.i

.PHONY : src/Part/Game/maps/Block/Bombe.i

# target to preprocess a source file
src/Part/Game/maps/Block/Bombe.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bombe.cpp.i
.PHONY : src/Part/Game/maps/Block/Bombe.cpp.i

src/Part/Game/maps/Block/Bombe.s: src/Part/Game/maps/Block/Bombe.cpp.s

.PHONY : src/Part/Game/maps/Block/Bombe.s

# target to generate assembly for a file
src/Part/Game/maps/Block/Bombe.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bombe.cpp.s
.PHONY : src/Part/Game/maps/Block/Bombe.cpp.s

src/Part/Game/maps/Block/Bonus/BombeUp.o: src/Part/Game/maps/Block/Bonus/BombeUp.cpp.o

.PHONY : src/Part/Game/maps/Block/Bonus/BombeUp.o

# target to build an object file
src/Part/Game/maps/Block/Bonus/BombeUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bonus/BombeUp.cpp.o
.PHONY : src/Part/Game/maps/Block/Bonus/BombeUp.cpp.o

src/Part/Game/maps/Block/Bonus/BombeUp.i: src/Part/Game/maps/Block/Bonus/BombeUp.cpp.i

.PHONY : src/Part/Game/maps/Block/Bonus/BombeUp.i

# target to preprocess a source file
src/Part/Game/maps/Block/Bonus/BombeUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bonus/BombeUp.cpp.i
.PHONY : src/Part/Game/maps/Block/Bonus/BombeUp.cpp.i

src/Part/Game/maps/Block/Bonus/BombeUp.s: src/Part/Game/maps/Block/Bonus/BombeUp.cpp.s

.PHONY : src/Part/Game/maps/Block/Bonus/BombeUp.s

# target to generate assembly for a file
src/Part/Game/maps/Block/Bonus/BombeUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bonus/BombeUp.cpp.s
.PHONY : src/Part/Game/maps/Block/Bonus/BombeUp.cpp.s

src/Part/Game/maps/Block/Bonus/PowerUp.o: src/Part/Game/maps/Block/Bonus/PowerUp.cpp.o

.PHONY : src/Part/Game/maps/Block/Bonus/PowerUp.o

# target to build an object file
src/Part/Game/maps/Block/Bonus/PowerUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bonus/PowerUp.cpp.o
.PHONY : src/Part/Game/maps/Block/Bonus/PowerUp.cpp.o

src/Part/Game/maps/Block/Bonus/PowerUp.i: src/Part/Game/maps/Block/Bonus/PowerUp.cpp.i

.PHONY : src/Part/Game/maps/Block/Bonus/PowerUp.i

# target to preprocess a source file
src/Part/Game/maps/Block/Bonus/PowerUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bonus/PowerUp.cpp.i
.PHONY : src/Part/Game/maps/Block/Bonus/PowerUp.cpp.i

src/Part/Game/maps/Block/Bonus/PowerUp.s: src/Part/Game/maps/Block/Bonus/PowerUp.cpp.s

.PHONY : src/Part/Game/maps/Block/Bonus/PowerUp.s

# target to generate assembly for a file
src/Part/Game/maps/Block/Bonus/PowerUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bonus/PowerUp.cpp.s
.PHONY : src/Part/Game/maps/Block/Bonus/PowerUp.cpp.s

src/Part/Game/maps/Block/Bonus/SpeedUp.o: src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.o

.PHONY : src/Part/Game/maps/Block/Bonus/SpeedUp.o

# target to build an object file
src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.o
.PHONY : src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.o

src/Part/Game/maps/Block/Bonus/SpeedUp.i: src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.i

.PHONY : src/Part/Game/maps/Block/Bonus/SpeedUp.i

# target to preprocess a source file
src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.i
.PHONY : src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.i

src/Part/Game/maps/Block/Bonus/SpeedUp.s: src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.s

.PHONY : src/Part/Game/maps/Block/Bonus/SpeedUp.s

# target to generate assembly for a file
src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.s
.PHONY : src/Part/Game/maps/Block/Bonus/SpeedUp.cpp.s

src/Part/Game/maps/Block/Breakable.o: src/Part/Game/maps/Block/Breakable.cpp.o

.PHONY : src/Part/Game/maps/Block/Breakable.o

# target to build an object file
src/Part/Game/maps/Block/Breakable.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Breakable.cpp.o
.PHONY : src/Part/Game/maps/Block/Breakable.cpp.o

src/Part/Game/maps/Block/Breakable.i: src/Part/Game/maps/Block/Breakable.cpp.i

.PHONY : src/Part/Game/maps/Block/Breakable.i

# target to preprocess a source file
src/Part/Game/maps/Block/Breakable.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Breakable.cpp.i
.PHONY : src/Part/Game/maps/Block/Breakable.cpp.i

src/Part/Game/maps/Block/Breakable.s: src/Part/Game/maps/Block/Breakable.cpp.s

.PHONY : src/Part/Game/maps/Block/Breakable.s

# target to generate assembly for a file
src/Part/Game/maps/Block/Breakable.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Breakable.cpp.s
.PHONY : src/Part/Game/maps/Block/Breakable.cpp.s

src/Part/Game/maps/Block/Ground.o: src/Part/Game/maps/Block/Ground.cpp.o

.PHONY : src/Part/Game/maps/Block/Ground.o

# target to build an object file
src/Part/Game/maps/Block/Ground.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Ground.cpp.o
.PHONY : src/Part/Game/maps/Block/Ground.cpp.o

src/Part/Game/maps/Block/Ground.i: src/Part/Game/maps/Block/Ground.cpp.i

.PHONY : src/Part/Game/maps/Block/Ground.i

# target to preprocess a source file
src/Part/Game/maps/Block/Ground.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Ground.cpp.i
.PHONY : src/Part/Game/maps/Block/Ground.cpp.i

src/Part/Game/maps/Block/Ground.s: src/Part/Game/maps/Block/Ground.cpp.s

.PHONY : src/Part/Game/maps/Block/Ground.s

# target to generate assembly for a file
src/Part/Game/maps/Block/Ground.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Ground.cpp.s
.PHONY : src/Part/Game/maps/Block/Ground.cpp.s

src/Part/Game/maps/Block/Metal.o: src/Part/Game/maps/Block/Metal.cpp.o

.PHONY : src/Part/Game/maps/Block/Metal.o

# target to build an object file
src/Part/Game/maps/Block/Metal.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Metal.cpp.o
.PHONY : src/Part/Game/maps/Block/Metal.cpp.o

src/Part/Game/maps/Block/Metal.i: src/Part/Game/maps/Block/Metal.cpp.i

.PHONY : src/Part/Game/maps/Block/Metal.i

# target to preprocess a source file
src/Part/Game/maps/Block/Metal.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Metal.cpp.i
.PHONY : src/Part/Game/maps/Block/Metal.cpp.i

src/Part/Game/maps/Block/Metal.s: src/Part/Game/maps/Block/Metal.cpp.s

.PHONY : src/Part/Game/maps/Block/Metal.s

# target to generate assembly for a file
src/Part/Game/maps/Block/Metal.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Metal.cpp.s
.PHONY : src/Part/Game/maps/Block/Metal.cpp.s

src/Part/Game/maps/Block/Rock.o: src/Part/Game/maps/Block/Rock.cpp.o

.PHONY : src/Part/Game/maps/Block/Rock.o

# target to build an object file
src/Part/Game/maps/Block/Rock.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Rock.cpp.o
.PHONY : src/Part/Game/maps/Block/Rock.cpp.o

src/Part/Game/maps/Block/Rock.i: src/Part/Game/maps/Block/Rock.cpp.i

.PHONY : src/Part/Game/maps/Block/Rock.i

# target to preprocess a source file
src/Part/Game/maps/Block/Rock.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Rock.cpp.i
.PHONY : src/Part/Game/maps/Block/Rock.cpp.i

src/Part/Game/maps/Block/Rock.s: src/Part/Game/maps/Block/Rock.cpp.s

.PHONY : src/Part/Game/maps/Block/Rock.s

# target to generate assembly for a file
src/Part/Game/maps/Block/Rock.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/maps/Block/Rock.cpp.s
.PHONY : src/Part/Game/maps/Block/Rock.cpp.s

src/Part/Game/player/ComputerAi.o: src/Part/Game/player/ComputerAi.cpp.o

.PHONY : src/Part/Game/player/ComputerAi.o

# target to build an object file
src/Part/Game/player/ComputerAi.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/player/ComputerAi.cpp.o
.PHONY : src/Part/Game/player/ComputerAi.cpp.o

src/Part/Game/player/ComputerAi.i: src/Part/Game/player/ComputerAi.cpp.i

.PHONY : src/Part/Game/player/ComputerAi.i

# target to preprocess a source file
src/Part/Game/player/ComputerAi.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/player/ComputerAi.cpp.i
.PHONY : src/Part/Game/player/ComputerAi.cpp.i

src/Part/Game/player/ComputerAi.s: src/Part/Game/player/ComputerAi.cpp.s

.PHONY : src/Part/Game/player/ComputerAi.s

# target to generate assembly for a file
src/Part/Game/player/ComputerAi.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/player/ComputerAi.cpp.s
.PHONY : src/Part/Game/player/ComputerAi.cpp.s

src/Part/Game/player/Human.o: src/Part/Game/player/Human.cpp.o

.PHONY : src/Part/Game/player/Human.o

# target to build an object file
src/Part/Game/player/Human.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/player/Human.cpp.o
.PHONY : src/Part/Game/player/Human.cpp.o

src/Part/Game/player/Human.i: src/Part/Game/player/Human.cpp.i

.PHONY : src/Part/Game/player/Human.i

# target to preprocess a source file
src/Part/Game/player/Human.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/player/Human.cpp.i
.PHONY : src/Part/Game/player/Human.cpp.i

src/Part/Game/player/Human.s: src/Part/Game/player/Human.cpp.s

.PHONY : src/Part/Game/player/Human.s

# target to generate assembly for a file
src/Part/Game/player/Human.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Game/player/Human.cpp.s
.PHONY : src/Part/Game/player/Human.cpp.s

src/Part/Menu/Menu.o: src/Part/Menu/Menu.cpp.o

.PHONY : src/Part/Menu/Menu.o

# target to build an object file
src/Part/Menu/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/Menu.cpp.o
.PHONY : src/Part/Menu/Menu.cpp.o

src/Part/Menu/Menu.i: src/Part/Menu/Menu.cpp.i

.PHONY : src/Part/Menu/Menu.i

# target to preprocess a source file
src/Part/Menu/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/Menu.cpp.i
.PHONY : src/Part/Menu/Menu.cpp.i

src/Part/Menu/Menu.s: src/Part/Menu/Menu.cpp.s

.PHONY : src/Part/Menu/Menu.s

# target to generate assembly for a file
src/Part/Menu/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/Menu.cpp.s
.PHONY : src/Part/Menu/Menu.cpp.s

src/Part/Menu/PartMenu/ChooseMap.o: src/Part/Menu/PartMenu/ChooseMap.cpp.o

.PHONY : src/Part/Menu/PartMenu/ChooseMap.o

# target to build an object file
src/Part/Menu/PartMenu/ChooseMap.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/ChooseMap.cpp.o
.PHONY : src/Part/Menu/PartMenu/ChooseMap.cpp.o

src/Part/Menu/PartMenu/ChooseMap.i: src/Part/Menu/PartMenu/ChooseMap.cpp.i

.PHONY : src/Part/Menu/PartMenu/ChooseMap.i

# target to preprocess a source file
src/Part/Menu/PartMenu/ChooseMap.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/ChooseMap.cpp.i
.PHONY : src/Part/Menu/PartMenu/ChooseMap.cpp.i

src/Part/Menu/PartMenu/ChooseMap.s: src/Part/Menu/PartMenu/ChooseMap.cpp.s

.PHONY : src/Part/Menu/PartMenu/ChooseMap.s

# target to generate assembly for a file
src/Part/Menu/PartMenu/ChooseMap.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/ChooseMap.cpp.s
.PHONY : src/Part/Menu/PartMenu/ChooseMap.cpp.s

src/Part/Menu/PartMenu/Config.o: src/Part/Menu/PartMenu/Config.cpp.o

.PHONY : src/Part/Menu/PartMenu/Config.o

# target to build an object file
src/Part/Menu/PartMenu/Config.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/Config.cpp.o
.PHONY : src/Part/Menu/PartMenu/Config.cpp.o

src/Part/Menu/PartMenu/Config.i: src/Part/Menu/PartMenu/Config.cpp.i

.PHONY : src/Part/Menu/PartMenu/Config.i

# target to preprocess a source file
src/Part/Menu/PartMenu/Config.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/Config.cpp.i
.PHONY : src/Part/Menu/PartMenu/Config.cpp.i

src/Part/Menu/PartMenu/Config.s: src/Part/Menu/PartMenu/Config.cpp.s

.PHONY : src/Part/Menu/PartMenu/Config.s

# target to generate assembly for a file
src/Part/Menu/PartMenu/Config.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/Config.cpp.s
.PHONY : src/Part/Menu/PartMenu/Config.cpp.s

src/Part/Menu/PartMenu/Credit.o: src/Part/Menu/PartMenu/Credit.cpp.o

.PHONY : src/Part/Menu/PartMenu/Credit.o

# target to build an object file
src/Part/Menu/PartMenu/Credit.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/Credit.cpp.o
.PHONY : src/Part/Menu/PartMenu/Credit.cpp.o

src/Part/Menu/PartMenu/Credit.i: src/Part/Menu/PartMenu/Credit.cpp.i

.PHONY : src/Part/Menu/PartMenu/Credit.i

# target to preprocess a source file
src/Part/Menu/PartMenu/Credit.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/Credit.cpp.i
.PHONY : src/Part/Menu/PartMenu/Credit.cpp.i

src/Part/Menu/PartMenu/Credit.s: src/Part/Menu/PartMenu/Credit.cpp.s

.PHONY : src/Part/Menu/PartMenu/Credit.s

# target to generate assembly for a file
src/Part/Menu/PartMenu/Credit.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/Credit.cpp.s
.PHONY : src/Part/Menu/PartMenu/Credit.cpp.s

src/Part/Menu/PartMenu/HowToPlay.o: src/Part/Menu/PartMenu/HowToPlay.cpp.o

.PHONY : src/Part/Menu/PartMenu/HowToPlay.o

# target to build an object file
src/Part/Menu/PartMenu/HowToPlay.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/HowToPlay.cpp.o
.PHONY : src/Part/Menu/PartMenu/HowToPlay.cpp.o

src/Part/Menu/PartMenu/HowToPlay.i: src/Part/Menu/PartMenu/HowToPlay.cpp.i

.PHONY : src/Part/Menu/PartMenu/HowToPlay.i

# target to preprocess a source file
src/Part/Menu/PartMenu/HowToPlay.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/HowToPlay.cpp.i
.PHONY : src/Part/Menu/PartMenu/HowToPlay.cpp.i

src/Part/Menu/PartMenu/HowToPlay.s: src/Part/Menu/PartMenu/HowToPlay.cpp.s

.PHONY : src/Part/Menu/PartMenu/HowToPlay.s

# target to generate assembly for a file
src/Part/Menu/PartMenu/HowToPlay.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/Menu/PartMenu/HowToPlay.cpp.s
.PHONY : src/Part/Menu/PartMenu/HowToPlay.cpp.s

src/Part/PreScene.o: src/Part/PreScene.cpp.o

.PHONY : src/Part/PreScene.o

# target to build an object file
src/Part/PreScene.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/PreScene.cpp.o
.PHONY : src/Part/PreScene.cpp.o

src/Part/PreScene.i: src/Part/PreScene.cpp.i

.PHONY : src/Part/PreScene.i

# target to preprocess a source file
src/Part/PreScene.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/PreScene.cpp.i
.PHONY : src/Part/PreScene.cpp.i

src/Part/PreScene.s: src/Part/PreScene.cpp.s

.PHONY : src/Part/PreScene.s

# target to generate assembly for a file
src/Part/PreScene.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Part/PreScene.cpp.s
.PHONY : src/Part/PreScene.cpp.s

src/env/env.o: src/env/env.cpp.o

.PHONY : src/env/env.o

# target to build an object file
src/env/env.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/env/env.cpp.o
.PHONY : src/env/env.cpp.o

src/env/env.i: src/env/env.cpp.i

.PHONY : src/env/env.i

# target to preprocess a source file
src/env/env.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/env/env.cpp.i
.PHONY : src/env/env.cpp.i

src/env/env.s: src/env/env.cpp.s

.PHONY : src/env/env.s

# target to generate assembly for a file
src/env/env.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/env/env.cpp.s
.PHONY : src/env/env.cpp.s

src/graphic/Graphique.o: src/graphic/Graphique.cpp.o

.PHONY : src/graphic/Graphique.o

# target to build an object file
src/graphic/Graphique.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphic/Graphique.cpp.o
.PHONY : src/graphic/Graphique.cpp.o

src/graphic/Graphique.i: src/graphic/Graphique.cpp.i

.PHONY : src/graphic/Graphique.i

# target to preprocess a source file
src/graphic/Graphique.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphic/Graphique.cpp.i
.PHONY : src/graphic/Graphique.cpp.i

src/graphic/Graphique.s: src/graphic/Graphique.cpp.s

.PHONY : src/graphic/Graphique.s

# target to generate assembly for a file
src/graphic/Graphique.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphic/Graphique.cpp.s
.PHONY : src/graphic/Graphique.cpp.s

src/graphic/Sound.o: src/graphic/Sound.cpp.o

.PHONY : src/graphic/Sound.o

# target to build an object file
src/graphic/Sound.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphic/Sound.cpp.o
.PHONY : src/graphic/Sound.cpp.o

src/graphic/Sound.i: src/graphic/Sound.cpp.i

.PHONY : src/graphic/Sound.i

# target to preprocess a source file
src/graphic/Sound.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphic/Sound.cpp.i
.PHONY : src/graphic/Sound.cpp.i

src/graphic/Sound.s: src/graphic/Sound.cpp.s

.PHONY : src/graphic/Sound.s

# target to generate assembly for a file
src/graphic/Sound.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/graphic/Sound.cpp.s
.PHONY : src/graphic/Sound.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/save/save.o: src/save/save.cpp.o

.PHONY : src/save/save.o

# target to build an object file
src/save/save.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/save/save.cpp.o
.PHONY : src/save/save.cpp.o

src/save/save.i: src/save/save.cpp.i

.PHONY : src/save/save.i

# target to preprocess a source file
src/save/save.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/save/save.cpp.i
.PHONY : src/save/save.cpp.i

src/save/save.s: src/save/save.cpp.s

.PHONY : src/save/save.s

# target to generate assembly for a file
src/save/save.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/save/save.cpp.s
.PHONY : src/save/save.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... edit_cache"
	@echo "... src/Indie.o"
	@echo "... src/Indie.i"
	@echo "... src/Indie.s"
	@echo "... src/Part/Game/Game.o"
	@echo "... src/Part/Game/Game.i"
	@echo "... src/Part/Game/Game.s"
	@echo "... src/Part/Game/maps/BasicMap.o"
	@echo "... src/Part/Game/maps/BasicMap.i"
	@echo "... src/Part/Game/maps/BasicMap.s"
	@echo "... src/Part/Game/maps/Block/Animation.o"
	@echo "... src/Part/Game/maps/Block/Animation.i"
	@echo "... src/Part/Game/maps/Block/Animation.s"
	@echo "... src/Part/Game/maps/Block/Bombe.o"
	@echo "... src/Part/Game/maps/Block/Bombe.i"
	@echo "... src/Part/Game/maps/Block/Bombe.s"
	@echo "... src/Part/Game/maps/Block/Bonus/BombeUp.o"
	@echo "... src/Part/Game/maps/Block/Bonus/BombeUp.i"
	@echo "... src/Part/Game/maps/Block/Bonus/BombeUp.s"
	@echo "... src/Part/Game/maps/Block/Bonus/PowerUp.o"
	@echo "... src/Part/Game/maps/Block/Bonus/PowerUp.i"
	@echo "... src/Part/Game/maps/Block/Bonus/PowerUp.s"
	@echo "... src/Part/Game/maps/Block/Bonus/SpeedUp.o"
	@echo "... src/Part/Game/maps/Block/Bonus/SpeedUp.i"
	@echo "... src/Part/Game/maps/Block/Bonus/SpeedUp.s"
	@echo "... src/Part/Game/maps/Block/Breakable.o"
	@echo "... src/Part/Game/maps/Block/Breakable.i"
	@echo "... src/Part/Game/maps/Block/Breakable.s"
	@echo "... src/Part/Game/maps/Block/Ground.o"
	@echo "... src/Part/Game/maps/Block/Ground.i"
	@echo "... src/Part/Game/maps/Block/Ground.s"
	@echo "... src/Part/Game/maps/Block/Metal.o"
	@echo "... src/Part/Game/maps/Block/Metal.i"
	@echo "... src/Part/Game/maps/Block/Metal.s"
	@echo "... src/Part/Game/maps/Block/Rock.o"
	@echo "... src/Part/Game/maps/Block/Rock.i"
	@echo "... src/Part/Game/maps/Block/Rock.s"
	@echo "... src/Part/Game/player/ComputerAi.o"
	@echo "... src/Part/Game/player/ComputerAi.i"
	@echo "... src/Part/Game/player/ComputerAi.s"
	@echo "... src/Part/Game/player/Human.o"
	@echo "... src/Part/Game/player/Human.i"
	@echo "... src/Part/Game/player/Human.s"
	@echo "... src/Part/Menu/Menu.o"
	@echo "... src/Part/Menu/Menu.i"
	@echo "... src/Part/Menu/Menu.s"
	@echo "... src/Part/Menu/PartMenu/ChooseMap.o"
	@echo "... src/Part/Menu/PartMenu/ChooseMap.i"
	@echo "... src/Part/Menu/PartMenu/ChooseMap.s"
	@echo "... src/Part/Menu/PartMenu/Config.o"
	@echo "... src/Part/Menu/PartMenu/Config.i"
	@echo "... src/Part/Menu/PartMenu/Config.s"
	@echo "... src/Part/Menu/PartMenu/Credit.o"
	@echo "... src/Part/Menu/PartMenu/Credit.i"
	@echo "... src/Part/Menu/PartMenu/Credit.s"
	@echo "... src/Part/Menu/PartMenu/HowToPlay.o"
	@echo "... src/Part/Menu/PartMenu/HowToPlay.i"
	@echo "... src/Part/Menu/PartMenu/HowToPlay.s"
	@echo "... src/Part/PreScene.o"
	@echo "... src/Part/PreScene.i"
	@echo "... src/Part/PreScene.s"
	@echo "... src/env/env.o"
	@echo "... src/env/env.i"
	@echo "... src/env/env.s"
	@echo "... src/graphic/Graphique.o"
	@echo "... src/graphic/Graphique.i"
	@echo "... src/graphic/Graphique.s"
	@echo "... src/graphic/Sound.o"
	@echo "... src/graphic/Sound.i"
	@echo "... src/graphic/Sound.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/save/save.o"
	@echo "... src/save/save.i"
	@echo "... src/save/save.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

